networks:
  naucto:
    external: true

services:
  admin-panel:
    build:
      context: ..
      dockerfile: Admin-Panel/Dockerfile
    ports:
      - "${ADMIN_PORT:-3002}:80"
    restart: on-failure
    networks:
      - naucto
